# Generated by Django 6.0.3 on 2026-04-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_repositoryconfig_teammembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryconfig',
            name='knowledge_graph_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
