# Generated by Django 6.0.3 on 2026-04-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_repositoryconfig_teammembership'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequestevent',
            name='repository_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_request_events', to='teams.repositoryconfig'),
        ),
    ]
